### ISSUE TITLE
Matron 

### ISSUE THREAD

**Issue by jking-roar** [fiveofswords/botc-bot#5]
(from tt)
We have the means to reseat players. Just need to restrict whispers to neighbors.
if someone tries to whisper a non neighbor, probably print: "Matron is in play, you may only whisper your neighbors"
(or have the bot tell them who their neighbors are?)

----

(from tt)
Watched a matron game, realized the token only says (was changed to?) players must stay in seats. Perhaps we open this to neighbors within 2 of each player so it's less likely for someone to not be able to have meaningful chats.

Might be worth a bigger discussion when ready to be worked on.

**Comment by tt612** [comment]
With the creation of neighbor whispers, this might actually be implemented now?

**Comment by jking-roar** [comment]
if matron should only allow neighbor conversations, then yes, basic implementation is done

**Comment by jking-roar** [comment]
closing as basic implementation is done
